@baseUrl = http://localhost:5000

POST http://localhost:5000/send-mail
Content-Type: application/json

{
  "mails": "khameleonstorm@gmail.com",
  "subject": "testing logo",
  "message": "Heyy Spam added a new logo, lets see if it works"
}

###

