@baseUrl = http://localhost:5000

POST {{baseUrl}}/send-mail
Content-Type: application/json

{
  "mails": "beyndtech@gmail.com, khameleonstorm@gmail.com",
  "subject": "justtesting",
  "message": "Multi Email"
}

###

