@baseUrl = http://localhost:5000

POST https://bank-mail.vercel.app/send-mail
Content-Type: application/json

{
  "mails": "khameleonstorm@gmail.com",
  "subject": "justtesting",
  "message": "Multi Email"
}

###

